import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getSession } from "./supabase-server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  console.log(session);

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Header session={session} />
        {children}
      </body>
    </html>
  );
}
